version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 2
  reviewers:
  - benjello
  - adrienpacifico
  - sandcha
  labels:
  - kind:dependencies
  ignore:
  - dependency-name: ipykernel
    versions:
    - 5.4.3
    - 5.5.0
  - dependency-name: numpy
    versions:
    - 1.19.5
