version: 2
jobs:
  deps:
    working_directory: ~/tutorial
    docker:
      - image: python:3.7

    steps:
      - checkout:
          path: ~/tutorial

      - run:
          name: Create a virtualenv
          command: python -m venv /tmp/venv/tutorial

      - run:
          name: Install dependencies
          command: |
            source /tmp/venv/tutorial/bin/activate
            make install

      - persist_to_workspace:
          root: /tmp/venv/tutorial
          paths:
            - "*"

  test_notebooks:
    working_directory: ~/tutorial/notebooks
    docker:
      - image: python:3.7

    steps:
      - checkout:
          path: ~/tutorial

      - attach_workspace:
          at: /tmp/venv/tutorial

      - run:
          name: Test notebooks
          command: |
            source /tmp/venv/tutorial/bin/activate
            make test

workflows:
  version: 2
  build:
    jobs:
      - deps
      - test_notebooks:
          requires:
            - deps
