version: 2
jobs:
  deps:
    working_directory: ~/tutorial
    docker:
      - image: python:3.7

    steps:
      - checkout:
          path: ~/tutorial

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/tutorial
            python -m venv /tmp/venv/tutorial
            echo "source /tmp/venv/tutorial/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: make install

      - persist_to_workspace:
          root: /tmp/venv
          paths:
            - tutorial

  test_notebooks:
    working_directory: ~/tutorial/notebooks
    docker:
      - image: python:3.7

    steps:
      - checkout:
          path: ~/tutorial

    - attach_workspace:
        at: /tmp/venv

      - run:
          name: Test notebooks
          command: make test

workflows:
  version: 2
  build:
    jobs:
      - deps
      - test_notebooks
